'iPad':
  '2':
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  Air:
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  Retina:
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  # This has the same screen resolution as iPad 2; no simulator is available.
  # This is a valid test case using AppThwack.
  # Mini:
  #   - '7.0.3'
  #   - '7.1'
  #   - '8.0'
  #   - '8.1'
  #   - '8.2'

'iPhone':
  4s:
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  '5':
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  5s:
    - '7.0.3'
    - '7.1'
    - '8.0'
    - '8.1'
    - '8.2'
  '6':
    - '8.0'
    - '8.1'
    - '8.2'
  '6 Plus':
    - '8.0'
    - '8.1'
    - '8.2'
